### ISSUE TITLE
clarify recycling guidelines on website

### ISSUE THREAD

**Issue by sbdavies** [Ambridge/Ambridge#47]
Hello. We got a citation because there's a pile of cardboard boxes on our porch (we order online a lot). We would like to recycle them, but can't find anywhere to do so. I don't want to just throw them away. We also have some scrap wood and paint (and other chemicals like paint thinner, etc.) in our basement. I think that a lot of people just don't know where to dispose of paper, cardboard, chemicals, constructions materials, etc. We're trying to improve our house and this has been one of many things that makes it difficult. There's no way we can afford to rent a dumpster or pay someone to haul it.

I think that, if you get a citation for something like this, it would be helpful to include some options for resolving the issue.

Thanks in advance for your response.

**Comment by boydtl1** [comment]
Hi I own Recycled Dreams at the Silk House Café and we are always taking boxes and packing material here for use with our online store. We also repurpose furniture so paint, thinner and stripper are also welcome. Hope this helps to alleviate some of the stuff!
Terry

**Comment by cpenny86** [comment]
We've always just sent out paper and cardboard with the rest of the recyclables on garbage day. You can get a recycling bin at the DoItBest if you don't have one already.

http://www.myyp.com/guide/Ambridge,PA/Recyclable-Materials

**Comment by sbdavies** [comment]
@boydtl1 Thanks! I will see what can get to you. 

@cpenny86 Thank you for the link. I called the information line at the Borough a while ago, and they said that they don't recycle paper or cardboard, just glass and plastic.

**Comment by sbdavies** [comment]
@boydtl1 Most of the paint and stripper are pretty old. I'll see if any of it is still good.

**Comment by jmkauer** [comment]
Newsprint is able to be recycled with weekly pickup, it must be bundled and
/ or placed in your recycling bin.

Copy Paper, junk mail and again even newsprint can be recycled at the
Borough Building in the Green and Gold Paper Recycling Bin behind the Fire
Station.

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by sbdavies** [comment]
Thank you Mr. Kauer. So, just newspapers with the weekly pickup, though, if I am reading correctly? No other paper, and no cardboard?

**Comment by sbdavies** [comment]
(That would mean that the link that @cpenny86 provided is incorrect?)

**Comment by jmkauer** [comment]
No Cardboard with the weekly recycling.  Newsprint and regular paper is
acceptable with the recycling.

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by cpenny86** [comment]
... Seriously? All I know is that they've been collecting it all without a peep for a year and a half now.

**Comment by sbdavies** [comment]
@cpenny86 Maybe that means it's going in the garbage, not being recycled? :-(

**Comment by smkwolek** [comment]
I have never seen the guidelines posted earlier but when I checked them out they are not for Ambridge specifically. I usually see our guidelines once a year in one of the printed publications mailed to the house and it confirms what the Borough Manager said. My neighbors tell me that everything else is dumped and I have always wondered if you mix what isn't recycled if they even take time to sort it or if it all gets trashed. 

There are a lot of local resources for recycling odd items like construction refuse, appliances, batteries, etc. Google and be amazed. Of course it's an effort because you have to get your stuff to them. 

Also, the recycle dumpster at the Baden Borough Bldg parking lot is a great place for cardboard and paperboard. 

Sarah

**Comment by sbdavies** [comment]
Are the guidelines for Ambridge posted or available anywhere? 

I have Googled...and Googled...and Googled...

All I have found is Waste Management for disposing of hazardous materials. We called and left a message. We can try calling again. The DEP says to take them to your neighborhoods's hazardous waste disposal program, or, if your neighborhood doesn't have one, to divide it into small quantities and put it in the regular trash. I don't think we have such a program. 

As for appliances and other large items, I haven't seen anywhere to take those. Sometimes a guy will post on Craigslist he'll come and get old appliances, but I've never gotten any of them to call back. It's just frustrating, because I want to do the right thing - I'm aware we'll need to haul this stuff somewhere. Finding out WHERE has been a big project. (Unless you have the money to a pay company to come and take all the stuff you don't want.) None of my neighbors seem to know either. Are most people just throwing this stuff in the trash?

**Comment by cpenny86** [comment]
This sounds like information that would be very useful to have on the Boro website. Is there a way we can get the guidelines for waste / recycling / hazardous materials etc. more clearly posted there?

**Comment by sbdavies** [comment]
@cpenny86 Seconding your request.

**Comment by BergFulton** [comment]
@sbdavies 
I hear you! 
My husband and I had to clear out his parent's house and had a bunch of dangerous paint, chemicals, etc. We saved that for the hazardous chemical day that was put on down at Brady's Run Park. We did have to pay (it was really nominal, considering how much stuff we had, probably $14 with a AAA discount) and we had to wait in line and bring it, but it was overall a good experience and we got to get rid of it responsibly. 

In terms of the other stuff- I actually live in Harmony Twp, which does not recycle AT ALL. Not even glass and plastic. My husband and I have a strong moral objection to this, so we do a combination of:
* Take it to his parents house for their recycling day
* Take it to my parents house for their recycling day
* Cart it with us to the city and recycle it at the City of Pittsburgh public recycling point in the Strip on our way to work, which I believe does receive cardboard (it has been a while since I've recycled a lot of cardboard). 
* Paper and things I take to an Abitibi paper retriever at our church. 

Overall, getting rid of waste responsibly in our neighborhoods is...challenging. 

It looks like [Beaver County Recycling Center](http://www.beavercountypa.gov/waste-management/waste-management-recycling-instructions) will take it, but the hours of operation aren't that great, and they're over in Brady's Run, which is not necessarily easy for everyone to get to.

**Comment by whit537** [comment]
> Are the guidelines for Ambridge posted or available anywhere?
> This sounds like information that would be very useful to have on the Boro website. Is there a way we can get the guidelines for waste / recycling / hazardous materials etc. more clearly posted there?

I've updated the ticket title to be about this. @jmkauer Can you provide us a link if the info is already there?

**Comment by whit537** [comment]
I've reticketed adding cardboard to Ambridge's curb-side recycling program as #48.

Starting curb-side recycling in Harmony Twp is #13.

**Comment by cpenny86** [comment]
This is the info on the Boro site: http://www.ambridgeboro.org/index.asp?Type=B_DIR&SEC=%7BBA66C419-66F8-48B7-AE91-992723B664D9%7D&DE=%7BEF3B6E8A-2150-4F4B-8255-A4CD77A3B4D1%7D

It would be nice to have a clear list of what is/isn't accepted (including that newsprint will now be taken) -- right now it just says "glass, plastics, etc."

**Comment by whit537** [comment]
One suggestion I haven't seen yet: Waste Management has a consumer recycling drop-off point at their 23rd and Duss facility. There's a gate in the fence under this tree, with a dumpster on the other side of it. If the gate is closed you can leave stuff outside. That's where we take our cardboard, including packaging from Gluuteny on 8th Street where @JessWhit works.

![screen shot 2015-02-27 at 4 54 12 pm](https://cloud.githubusercontent.com/assets/134455/6421920/4d321f98-bea1-11e4-9ae4-ca224608114a.png)

https://www.google.com/maps/@40.603182,-80.226244,3a,30y,280.15h,87.82t/data=!3m4!1e1!3m2!1she43aQMQQTlyiNzw6BlRiw!2e0

**Comment by whit537** [comment]
@BergFulton Waste Management is actually right around the corner from you, I'm sorry I didn't realize you've been carting your recycling the whole way to Pittsburgh! :frowning:

**Comment by whit537** [comment]
Good find, @cpenny86. Hopefully @jmkauer can help us get that page updated with more specific info.

**Comment by whit537** [comment]
P.S. If we ever land #15, we'll be able to do the work ourselves. ;-)

**Comment by sbdavies** [comment]
Thanks, everyone. I guess we'll either take the cardboard to WM or Silk House. I wish we'd heard about that hazardous chemical day at Brady's Run.

**Comment by cpenny86** [comment]
@whit537 If we land #15, maybe we can change the urls as well -- ambridgeboro.org/recycling would be a lot easier to find than the mess I linked to above! (Wouldn't it be nice to migrate the whole thing to something like https://en.wordpress.com/cities/ ?)

**Comment by EileenFord** [comment]
cardboard recycling is conveniently done on Duss Avenue - almost directly across from Rhodes Transit - The Brunner site... when gates are open pull up to large garage doors and unload. - There are times listed on the gate - Usually they are daily (M-F) until 3pm I believe. I have been dropping cardboard there for 7 years.
Always help support the local kids/schools etc with your paper recyclables - The green & gold bins with ABBITIBI listed on them, - every piece of paper adds weight & they are fundaising through recycling they pay out according to weight - WIN WIN! Some of these bins were listed in another post - at location above (Borough property). One at Shop N Save, One at the Junior High School, one on the lot of Baden Academy Charter School, one at the Legion in Baden as well I believe.
If all else fails, list things on FREECYCLE- online website - if it is something someone can craft with - someone may come pick it up from you!!
To dry paint in order to put in garbage - spread on cardboard layer by layer until dry then throw in trash. Or use kitty litter to dry & absorb it. {Paint that has been outside/frozen or in extreme heat will not be usable for any projects.}
Building materials: Construction Junction will take many - East End of the cityin Beaver County - Habitat for Humanity - Beaver Falls area.
Hope this helps good luck Eileen Ford
email: blondej99@yahoo.com 

     On Friday, February 27, 2015 3:59 PM, Tracey Berg-Fulton <notifications@github.com> wrote:
   

 @sbdavies 
I hear you! 
My husband and I had to clear out his parent's house and had a bunch of dangerous paint, chemicals, etc. We saved that for the hazardous chemical day that was put on down at Brady's Run Park. We did have to pay (it was really nominal, considering how much stuff we had, probably $14 with a AAA discount) and we had to wait in line and bring it, but it was overall a good experience and we got to get rid of it responsibly. In terms of the other stuff- I actually live in Harmony Twp, which does not recycle AT ALL. Not even glass and plastic. My husband and I have a strong moral objection to this, so we do a combination of:   
   - Take it to his parents house for their recycling day
   - Take it to my parents house for their recycling day
   - Cart it with us to the city and recycle it at the City of Pittsburgh public recycling point in the Strip on our way to work, which I believe does receive cardboard (it has been a while since I've recycled a lot of cardboard). 
   - Paper and things I take to an Abitibi paper retriever at our church. 
Overall, getting rid of waste responsibly in our neighborhoods is...challenging. It looks like Beaver County Recycling Center will take it, but the hours of operation aren't that great, and they're over in Brady's Run, which is not necessarily easy for everyone to get to. —

**Comment by whit537** [comment]
Copying over from @jmkauer at https://github.com/Ambridge/Ambridge/issues/48#issuecomment-76717114: 

> As for posting a detailed recycling list on the website; no issue there. We'll get it up there soon and I'll report back.

**Comment by whit537** [comment]
@jmkauer When updating the recycling page on the Borough website, I propose that we also include information presented on this ticket regarding alternatives to curb-side recycling. Here are the suggestions I am seeing:

#### Recycling

 - [Beaver County Recycling Center](http://www.beavercountypa.gov/waste-management/waste-management-recycling-instructions) at Brady's Run takes many materials, and sponsors periodic hazardous waste collections. Fees may apply.
 - [Brunner](http://brunnerdisposal.com/) has a consumer drop-off point at their Duss Ave facility (across from Rhodes bus garage).
 - Waste Management has a consumer drop-off point at their 23rd and Duss facility.
 - Copy paper, junk mail and newsprint can be recycled in the Abitibi green and gold paper recycling bins at a number of locations around town (proceeds benefit local organizations).

#### Reuse

 - Some local businesses are willing to take boxes and packing material for use with their online stores. Stores that repurpose furniture may also be interested in paint, thinner, and stripper. List of businesses: Recycled Dreams at the Silk House Café.
 - Building materials can be taken to [Habit for Humanity ReStore](http://www.beavercountyhabitat.org/index.php?option=com_content&view=article&id=111&Itemid=179) or [Construction Junction](http://www.constructionjunction.org/).
 - Other unwanted items can be offered for reuse through [Goodwill](http://www.goodwillswpa.org/) or [Freecycle](https://groups.freecycle.org/group/PittsburghPA/posts/all).

**Comment by cpenny86** [comment]
I would add, for re-use, that the VVA will pick up donations of clothes, household items, small furniture, etc. http://www.scheduleapickup.com/

**Comment by jmkauer** [comment]
Ambridge Borough Website has been updated with Recycling and Trash Collection info.

Link:  http://www.ambridgeboro.org/index.asp?Type=B_DIR&SEC={BA66C419-66F8-48B7-AE91-992723B664D9}  

Thanks,
Joe Kauer
Borough Manager

**Comment by cpenny86** [comment]
Fantastic!

**Comment by sbdavies** [comment]
Great! Thank you!

**Comment by whit537** [comment]
Thanks @jmkauer! :-)
