### ISSUE TITLE
understand re-zoning/right-sizing

### ISSUE THREAD

**Issue by whit537** [Ambridge/Ambridge#60]
What's the story with the rezoning effort from the Downtown Development Council? I believe that relates to the facade grant program. Are other things affected by that, such as what businesses will be allowed in certain areas?

**Comment by jmkauer** [comment]
The concept of Right Sizing is a school of thought and an effort to sustain
a central business district that is walkable and that would contain the
right type of shops (retail, restaurants, specific service shops...) for a
healthy business environment of a traditional main street (IE:  review of
our current zoning to prohibit people for turning their Merchant St.
properties into cheap warehouses...)

The facade program is separate but incidental to the Right Sizing efforts.
   The ADDC is hoping to refocus the facade funds to Merchant Street only
between 4th and 16th Street.  The goal is to achieve a measurable statement
of rejuvenation by focusing on that core area to revitalize versus pretty
much the entire commercial zoning districts of the Borough.

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by kjc3tacoma** [comment]
This sounds like a very good idea.  As stated in the article the main street is very long and no longer viable to maintain business in every vacant building.  It would be nice to see more family restaurant type business instead of so many bars that look to be havens of ill repute.  It's easy to say but takes money to do this of course and folks willing to spend that money.  Hopefully over time it will happen.  I would rather spend my money close to home instead of having to travel to Center Twp,/Cranberry/ or Robinson to take my family to dinner in a family friendly environment.

**Comment by whit537** [comment]
I suppose we've taken this as far as the title allows. Any more questions about right-sizing, ask away! :-)
