### ISSUE TITLE
Info and help on 19th & Duss

### ISSUE THREAD

**Issue by smkwolek** [Ambridge/Ambridge#63]
I'm curious what they are building behind 19th & Duss in the Industrial Park. I also would appreciate more police interaction with the construction guys on the site who have Ohio plates and consistently drive on 19th Street the wrong direction (nearly hitting my car on numerous occasions in the past few weeks). I sometimes wonder if one way signs are not used in Ohio as these drivers do not seem to understand what they are.

**Comment by jmkauer** [comment]
The construction behind 19th and Duss is by the Ambridge Municipal
Authority.  It is part of their efforts to comply to the EPA consent order
regarding the Sanitary Sewer System.  The site will be storage tank needed
for the system.  More info:

AMBRIDGE MUNICIPAL AUTHORITY TO START PARK ROAD SEWER PROJECT ON MONDAY,
MARCH 30TH

Since 2001, the Borough of Ambridge Municipal Authority has worked under
order of the PA Department of Environmental Protection to correct the
sanitary sewer system in order to eliminate all discharges of sewage from
the system to the waters of the Commonwealth. The Authority has mapped
their system, located and eliminated sources of storm water entrance to the
system, completed corrections and repairs to the facilities, updated
wastewater treatment plant, updated pump stations and completed flow
monitoring studies to determine system improvements required to eliminate
all sewage overflows.

After formal approval by the PADEP of corrective facilities necessary, in
recent months, the Authority has initiated contracts for substantial
capital projects to improve the performance of our sanitary sewer system
and meet required environmental standards, including:

· Park Rd relief sewer line from 8th to 4th
· New 4th Street Pump Station &* demolition of existing.
· New Pump Station Force Main from 4th St to 19th St via Park, Ohioview,
Church & SR65.
· Rehabilitation of Existing Force Main along SR 65 from 4th to 10th.
· New storm storage facility at 19th St & Oak.

Construction of thee projects began with site work and grading at the Storm
Storage Facility near 19th Street and work on the relief sewer line along
Park Rd is proposed to start on March 30th. The other projects will begin
soon thereafter at their various locations around the Borough.

Each project will create some temporary disruptions at different timings to
normal patterns of life in Ambridge Borough. Projects will extend into the
Spring of 2016. Every effort will be made to communicate to the residents
of Ambridge Borough the impact of these construction activities in specific
areas before they begin. The Borough website and facebook page will be
regularly updated and will remain a good source of information during the
coming year. Other local news outlets will also be involved.

Thank you for you patience and understanding as we make these very
important permanent improvements to the sanitary system of our fine Borough.

For questions or additional information, call the Authority Office at
724-266-7810.

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by whit537** [comment]
Thanks for the info @jmkauer. Are you able to pass on to the police department the report about not observing the one-way signs?

> I also would appreciate more police interaction with the construction guys on the site who have Ohio plates and consistently drive on 19th Street the wrong direction (nearly hitting my car on numerous occasions in the past few weeks).

**Comment by jmkauer** [comment]
Will do.

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by smkwolek** [comment]
Thank you! Much appreciated.

 I'm also noticing that the street is becoming a bit like a construction site with a lot of dirt, debris and rocks. I'm hopeful I won't lose any tires during this project since the Borough only offers me one direction out of my garage on Oak and it requires driving on 19th. 

Sarah

Mark & Sarah Kwolek
724.462.5764 Sarah Cell
724.462.5830 Mark Cell

**Comment by whit537** [comment]
We good to close this issue, @smkwolek? If there are additional action items needed here please respond/reopen. Thanks! :-)
